services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: users
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app-network
  #   ports:
  #     - "3000:3000"

networks:
  app-network:

volumes:
  mysql-data:
