version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DB_HOST: mysqldb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:

volumes:
  mysql-data:
