# Etapa de instalação de dependências
FROM node:18-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Etapa de build da aplicação
FROM node:18-alpine AS build
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=production
RUN npm run build
# Adiciona permissão para os scripts aqui
RUN chmod +x ./scripts/server.sh ./scripts/wait-for-it.sh  

# Etapa de execução final
FROM node:18-alpine AS runtime
WORKDIR /home/node/app
USER node
ENV NODE_ENV=production

# Copia os arquivos do sequelize
COPY --chown=node:node .env.test /home/node/app/.env.production
COPY --chown=node:node .sequelizerc.prod /home/node/app/.sequelizerc
# Copia apenas arquivos essenciais para a execução
COPY --chown=node:node --from=dependencies /app/node_modules ./node_modules
COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node --from=build /app/scripts ./scripts

# Define o entrypoint para iniciar a aplicação
ENTRYPOINT ["./scripts/wait-for-it.sh", "mysqldb:3306", "--timeout=30", "--strict", "--", "./scripts/server.sh"]
